### ISSUE TITLE
RX - TX Swapped in PDF schema

### ISSUE THREAD

**Issue by miqmago** [codm/cc2538-raspberry-pi-module#1]
I've seen that RX and TX are swapped in JP1, Is that right?

Raspberry PI Pinout https://www.raspberrypi.org/documentation/usage/gpio/:
```

            3V3| 1 | 2  |5V
    GPIO2 (SDA)| 3 | 4  |5V
    GPIO3 (SCL)| 5 | 6  |GND
 GPIO4 (GPCLK0)| 7 | 8  |GPIO14 (TXD)
            GND| 9 | 10 |GPIO15 (RXD)
```

But in https://github.com/codm/cc2538-raspberry-pi-module/blob/master/rpi-cc2538-uart.sch.pdf the JP1 header is configured like this:

```
   | 1 | 2  |VCC
   | 3 | 4  |
GND| 5 | 6  |
RXD| 7 | 8  |
TXD| 9 | 10 |GND
```

**Comment by codmpm** [comment]
Hey @miqmago, yes that is correct. 
TX is where the data is sent from (transceived), so at the Pi that data is received. Thus TX is connected to RX and vice versa.

The boards we currently sell are based on this repo, so they do work.
