### ISSUE TITLE
Gerber and BOM

### ISSUE THREAD

**Issue by ghost** [codm/cc2538-raspberry-pi-module#2]
Any plans to release Gerber and BOM for this? It looks like it's impossible to order prebuild board from russia, so it would be great if one could just manufacture this without having to go to CAM processing in Eagle first...

**Comment by codmpm** [comment]
Hey @Unb9rn,

as the gerbers should be deppendant on the DRU files from the board house, it should be better to generate them with Eagle accordingly. Should be possible with the free variant.

The BOM is rather simple and could also be exported from eagle.

Cheers,
Patrik
